In [1]:
print("hello ")

hello 


In [7]:
nu=int(input("Enter a number"))
if(nu ==0):
    print("Zero an")
elif(nu >0):
    print("+ve man")
else:
    print("-ve woman")

Enter a number9
+ve man


In [3]:
import django
help(django)



Help on package django:

NAME
    django

PACKAGE CONTENTS
    __main__
    apps (package)
    conf (package)
    contrib (package)
    core (package)
    db (package)
    dispatch (package)
    forms (package)
    http (package)
    middleware (package)
    shortcuts
    template (package)
    templatetags (package)
    test (package)
    urls (package)
    utils (package)
    views (package)

FUNCTIONS
    setup(set_prefix=True)
        Configure the settings (this happens as a side effect of accessing the
        first setting), configure logging and populate the app registry.
        Set the thread-local urlresolvers script prefix if `set_prefix` is True.

DATA
    VERSION = (2, 0, 4, 'final', 0)

VERSION
    2.0.4

FILE
    c:\users\dawud\appdata\local\programs\python\python36-32\lib\site-packages\django\__init__.py




In [4]:
import django
print(django.get_version())

2.0.4


In [1]:
import numpy as np

In [3]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [6]:
np.arange(0,100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [84]:
np.arange(0,100).reshape(10,10) + np.arange(10,110).reshape(10,10) 

array([[ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 30,  32,  34,  36,  38,  40,  42,  44,  46,  48],
       [ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148],
       [150, 152, 154, 156, 158, 160, 162, 164, 166, 168],
       [170, 172, 174, 176, 178, 180, 182, 184, 186, 188],
       [190, 192, 194, 196, 198, 200, 202, 204, 206, 208]])

In [85]:
np.arange(10,101,2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

In [116]:
np.random.randint(1,100, 10)

array([53, 61, 14, 37, 99, 77, 60, 46, 51, 49])

In [89]:
np.random.randn(20).reshape(4,5)

array([[-0.69269763, -0.8604376 ,  0.48558611,  0.38259961, -1.016418  ],
       [ 0.4043485 , -0.69009898,  0.3440877 , -0.72267268, -1.34273181],
       [ 0.64829614,  0.10078758,  0.06362458, -0.27755682, -0.07073153],
       [ 0.20270229, -1.19912548,  0.23970297, -1.95414682,  1.02808816]])

In [106]:
np.random.rand(100).reshape(10,10)

array([[ 0.22959837,  0.7882497 ,  0.75657442,  0.91736748,  0.91391672,
         0.53336876,  0.04165899,  0.50841406,  0.01891817,  0.35388504],
       [ 0.30422334,  0.91198389,  0.96242666,  0.22839733,  0.45665269,
         0.89836422,  0.57899925,  0.33850771,  0.91859178,  0.65763351],
       [ 0.48319019,  0.06846061,  0.94724785,  0.92918205,  0.95420205,
         0.251805  ,  0.14095027,  0.10139608,  0.7856218 ,  0.56882312],
       [ 0.06589246,  0.35010959,  0.20091104,  0.43671059,  0.45723046,
         0.87672515,  0.62656929,  0.17244953,  0.4376965 ,  0.32737141],
       [ 0.12266479,  0.26404931,  0.02272703,  0.10596476,  0.46319783,
         0.90942066,  0.74629199,  0.12116272,  0.96990654,  0.29944246],
       [ 0.30797215,  0.7342672 ,  0.42640813,  0.39358803,  0.96802577,
         0.33550695,  0.62920389,  0.07637818,  0.269503  ,  0.62422777],
       [ 0.60601509,  0.13910277,  0.71872421,  0.8769468 ,  0.63317773,
         0.84764534,  0.58848548,  0.08357088

In [102]:
np.arange(1,101).reshape(10,10) / 100

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [114]:
# use to create an evenly distibuted array of numbers
np.linspace(0,100, 20) 

array([   0.        ,    5.26315789,   10.52631579,   15.78947368,
         21.05263158,   26.31578947,   31.57894737,   36.84210526,
         42.10526316,   47.36842105,   52.63157895,   57.89473684,
         63.15789474,   68.42105263,   73.68421053,   78.94736842,
         84.21052632,   89.47368421,   94.73684211,  100.        ])

In [83]:
listy = [1,2,3,4,5,6,7,8,9,8]
np.array(listy)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 8])